version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "7000:7000"
    depends_on:
      - backend
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: chuchmek@zerocorp.uz
      PGADMIN_DEFAULT_PASSWORD: ChuchmekNaShahzode2417!
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
networks:
  app-network:
    driver: bridge
